[package]
name = "sleepy-not"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlib-face-recognition = "0.3.2"
image = "0.25.1"
opencv = "0.89.0"
rodio = "0.17.3"
